### ISSUE TITLE
Packagist returns 404 on some of json for composer v2

### ISSUE THREAD

**Issue by sprymiker** [composer/packagist#1134]
## Problem
We have 404 errors on some (120) of our modules. So `composer update` fails with multiple errors.

## Env
Any composer v2: **2.0.2** or master.
Composer v1 updates everything without errors.

## Behavior

```
composer update
```
```
...
[404] https://repo.packagist.org/p2/spryker/merchant-user-gui~dev.json
[404] https://repo.packagist.org/p2/spryker/merchants-rest-api~dev.json
...
```

```
  Problem 119
    - spryker-shop/merchant-product-offer-widget[0.11.0, 0.11.1] require spryker/merchant-storage ^0.1.0 -> found spryker/merchant-storage[0.1.2] in lock file but not in remote repositories, make sure you avoid updating this package to keep the one from lock file.
```

## Example of 404:

https://repo.packagist.org/packages/spryker/merchant-storage - everything OK
https://repo.packagist.org/p2/spryker/merchant-storage~dev.json - 404

**Comment by Seldaek** [comment]
Ok thanks, please do not commit anything to it if possible while I investigate.

**Comment by matweew** [comment]
I got similar issue, but composer v2 could not download public symfony packages and requested to add GitHub access token.

**Comment by Seldaek** [comment]
Alright, I found the issue. I fixed the root cause but it'll still take a while for all our mirrors to resync and have all files made available. I'll confirm once it's done.

**Comment by Seldaek** [comment]
@matweew your issue sounds completely unrelated, please report a new one with details instead of hijacking this thread.

**Comment by sprymiker** [comment]
@Seldaek The problem still persists.

https://repo.packagist.org/p2/spryker/merchant-storage~dev.json still - 404.
https://www.site24x7.com/check-website-availability.html reports that the URL is not accessible from different geo-locations. So it is not me only.

And composer update behaves the same way.

Do we need to wait more? Or the problem is not fixed yet? What actions should perform to fix that from our side?

**Comment by Seldaek** [comment]
@sprymiker I see the file on all servers now, but I see the package got updated 10minutes after you wrote here, so that probably fixed it.. I took a more drastic approach and looked at all spryker packages now and I am seeing some issues still for sure. There's another issue at the very root of the metadata, on top of the mirroring issue I fixed earlier. Still investigating, hopefully can fix it soon.

**Comment by Seldaek** [comment]
Ok figured out it was actually another side effect of the issue I solved earlier.. Looks like you should be really back on track now.

**Comment by Seldaek** [comment]
FWIW, confirmed that all our mirrors now have the 797 spryker packages present 👍

**Comment by sprymiker** [comment]
Thank you very much, @Seldaek. It works properly now.

```
Dependency resolution completed in 0.013 seconds
Lock file operations: 0 installs, 45 updates, 0 removals
```

**Comment by henrywhitaker3** [comment]
Think I'm having similar issues for a new package I submitted this morning:

```
Running 2.0.9 (2021-01-27 16:09:27) with PHP 7.4.9 on Linux / 5.8.0-7630-generic
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /home/henry/.cache/composer/repo/https---repo.packagist.org/packages.json into cache
Downloading https://repo.packagist.org/p2/henrywhitaker3/laravel-actions.json
Downloading https://repo.packagist.org/p2/henrywhitaker3/laravel-actions~dev.json
[404] https://repo.packagist.org/p2/henrywhitaker3/laravel-actions.json
[404] https://repo.packagist.org/p2/henrywhitaker3/laravel-actions~dev.json
Downloading https://packagist.org/search.json?q=henrywhitaker3/laravel-actions&type=
[200] https://packagist.org/search.json?q=henrywhitaker3/laravel-actions&type=

                                                          
  [InvalidArgumentException]                              
  Could not find package henrywhitaker3/laravel-actions.  
                                                          
  Did you mean this?                                      
      henrywhitaker3/laravel-actions                      
```
