### ISSUE TITLE
Allow users to delete new packages

### ISSUE THREAD

**Issue by naderman** [composer/packagist#166]
We should allow users to delete new packages (recently created & few installs) so that mistakenly added packages can be removed without danger of projects depending on them already.

**Comment by FlorianKoerner** [comment]
Please delete:

- https://packagist.org/packages/checkdomain/mailchimp-bundle
- https://packagist.org/packages/checkdomain/mandrill-bundle
- https://packagist.org/packages/checkdomain/clickatell-bundle

**Comment by mmansoorebay** [comment]
@Seldaek
Please delete:
https://packagist.org/packages/magento/product-community-edition
It's an incorrectly configured package (has a recursive dependency on itself so it will not install properly) and is also no longer maintained.
The correct package is at magento/project-community-edition.

**Comment by Seldaek** [comment]
Done

**Comment by vancoz** [comment]
Hello @Seldaek, thank you, we found that https://packagist.org/packages/magento/product-community-edition is deleted and we can not fins it on web interface.
But it is still exists in composer cache even after clearcache:
 ~/.composer/cache/repo/https---packagist.org/provider-magento\$product-community-edition.json  

May you refresh packages.json or suggest how to fix it?
Thank you

**Comment by Seldaek** [comment]
Is it really a big problem that it still is in the json data? I can 
flush it from there but that takes quite a while as right now we don't 
handle deletions very well, and I'd rather not do that for nothing.

**Comment by vancoz** [comment]
Hi @Seldaek, yes it is really big issue.
We have moved https://packagist.org/packages/magento/product-community-edition to our internal composer repo and this one points to wrong git repo. Current on packagist the package has itself in requirement. Please remove it from cache.

**Comment by Seldaek** [comment]
But if you define your own custom repository it should take that package 
instead of loading it from packagist, so I don't really see how that's a 
problem, anyway I'll run a cleanup tomorrow morning.

**Comment by vancoz** [comment]
@Seldaek, there is few issues actually.

1. Our users tries to use old package without defining new repo.
2. We have few repos, and in case if we have defined more than one custom repo - composer tries to get package info from packagist cache.

**Comment by vancoz** [comment]
Hello @Seldaek, have you any updates or suggestions?

**Comment by Seldaek** [comment]
Ok it should be removed now, sorry for the delay

**Comment by vancoz** [comment]
@Seldaek, thank you, appreciate it.

**Comment by hamidabbaszadeh** [comment]
Please delete the following package:
https://packagist.org/packages/respinar/catalog
https://packagist.org/packages/respinar/persiandate

**Comment by Seldaek** [comment]
Done

**Comment by maximkott** [comment]
Please delete this package:
https://packagist.org/packages/weew/php-foundation

**Comment by Seldaek** [comment]
Done, in the future though please reach out to contact@packagist.org to request package deletions to avoid spamming everyone in here. I'll lock this issue now.
