### ISSUE TITLE
Github README links are broken

### ISSUE THREAD

**Issue by sagikazarmark** [composer/packagist#520]
A common practice is to place a link CONTRIBUTING guide and LICENSE in the README. Since they are on the same path, they can easily be relatively linked (eg. `[CONTRIBUTING](CONTRIBUTING.md)`). These links are broken now on packagist as it reads the README file of the package.

Not sure if it's possible, but AFAIK there is a way to generate HTML from MD using Github API calls.

**Comment by neomerx** [comment]
+1

**Comment by Seldaek** [comment]
I use the github HTML generation but they don't resolve links, that said it's still possible to resolve relative links as we know the base URL. Shouldn't be too hard.

**Comment by stof** [comment]
I suggest sending a mail to the Github support to ask for link resolution in rendered readme in the API. It looks more sensible than forcing clients of their API to resolve them again.

**Comment by Seldaek** [comment]
GitHub support passed it on to team but that might take a while to happen, so I pushed a fix in the meantime.

**Comment by neomerx** [comment]
@Seldaek Still broken.

https://packagist.org/packages/neomerx/json-api link `Sample App` broken

**Comment by Seldaek** [comment]
It's fixed now for that package, since the transforms happen on update it'll take a while for broken readme to be updated but on new updates it works.

**Comment by sagikazarmark** [comment]
@Seldaek thanks :+1:
