### ISSUE TITLE
README convert relative images and links to absolute ones

### ISSUE THREAD

**Issue by kaystrobach** [composer/packagist#532]
e.g for https://packagist.org/packages/kaystrobach/development-tools i use images in the README.md the images are not shown on packagist, But on github, as I use relative resource identifier for storing in the README

**Comment by alcohol** [comment]
This should be fixed by a86f0709d2fd387a209dbba8eeb32332a295ee9d already.

**Comment by stof** [comment]
note that the fix is done when reading the readme from github during package updates. so it will be fixed for your package only the next time the repo is updated

**Comment by stof** [comment]
@alcohol actually, this commit does not fix it. It handles relative links, but not relative image sources.

**Comment by alcohol** [comment]
In that case it should be implemented I guess. Shouldn't be too hard :-)
